apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: prod
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames: ["prod"]
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
